---
apiVersion: v1
kind: Service
metadata:
  name: booking-stable
spec:
  selector:
    app: booking
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: booking-preview
spec:
  selector:
    app: booking
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
  