---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger
  labels:
    app.kubernetes.io/name: passenger
    app.kubernetes.io/part-of: booking-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passenger
  template:
    metadata:
      labels:
        app: passenger
    spec:
      imagePullSecrets:
        - name: github
      containers:
        # CHANGE TO YOURS:<org/repo:tag>
        - image: ghcr.io/asmaestro/bm-passenger:latest
          name: passenger
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: docker
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 512Mi
              cpu: 256m
  # strategy:
  #   canary: 
      # canaryService: passenger-canary
      # stableService: passenger-stable
      # trafficRouting:
      #   nginx:
      #     stableIngress: booking-microservies
      # steps:
      # - setWeight: 20
      # - pause: {}