apiVersion: v1
kind: Secret
metadata:
    name: secret-using-sops
type: Opaque
data:
    password: ENC[AES256_GCM,data:SkQcpibKeKBrDtQHbFaSgQ==,iv:NdIWDB8g2Lw+dtsGEi+5LgahOVcdxMeGo/qMlGSvb1w=,tag:2WOQHs7ZfzJ6v3vwQKz3WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13t0u3c3lx4djsdmwaqnamr4jqkdyuznasjw2h7xn3753qwtdgqqs3fgcul
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T0JpWERwYmd6VzRIdExs
            ZW5jMzZuTXFYOFNvOGpXSmZMbHlmYzhkWVcwCnZmNTlOMTR0QXE4Rkl0QVRMZHRV
            d3JpaTY1cnJ6RjVuamI1bWxUV0kxZEEKLS0tIFMyZ2Q2YkJrQUpMSFhqa1FkSHo5
            bFJKWW9QVHVkajNNRUFjcWV3cmtsWjgKY+yCRQHblK5irg8200p6jxSuCkQPeZ/1
            nnXFdOhtv3BVk805NXSaP4Pi9uanmUgxKzweUUyWzAVqpfIg5BdUQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T11:38:33Z"
    mac: ENC[AES256_GCM,data:T+Cm7owkAlTpyeau03zJwGL62eAN7BpgPRDDjM2a4ywcz+c8cNcMkM/naBgjtF1xqpkx1AEKRzPNn3Io/ZUbkEgERIlz8oOfoiQ7MPnWj65UbHD4BjH/DPFX9tZqSWU9Wv+hI1ztbfod9jREwWgllc5dt/n3csq1rACjhothsDg=,iv:aDcpIDIYxq0l11wpz8ExmDl0NZBGfx8kjF1CY5Z1DxI=,tag:C+wJgGnKUNjRUl+PRTTABg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
