apiVersion: v1
kind: Secret
metadata:
    name: secret-using-sops
type: Opaque
data:
    password: ENC[AES256_GCM,data:cA5Ufhk67JLMS7icGWucnQ==,iv:80f7T8VEKw6hQmWHlu+Tw+O3INZ/zb/2XLzCdtwm5J0=,tag:KuG7X+kBMzrH01ysW6Q1lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13t0u3c3lx4djsdmwaqnamr4jqkdyuznasjw2h7xn3753qwtdgqqs3fgcul
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRGhEcFppQ0ZyNEtueGRa
            VEhZQ3JNOFJ4Y01QWVBvL0JQRFVYdE1SaGt3Ck9TcFVyQUNia003TjhrU0JNUTB1
            WHhvMWIyekEydGt1WHBPVDhVaU9JaGMKLS0tIER4WXkwNmxTa2tsRVozWG5pY2pZ
            UFlaTHJFYk9VNzhCNXFNQ3ZTT2JPMW8K0w+s2aH/Yph6aofAhc2ypQsR5E75IwSg
            QGdq1rgc9nybE4nA+pvtOoiC/vDdmQfwxGZK2UmozVJ8PQ/bfh4vgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T08:15:19Z"
    mac: ENC[AES256_GCM,data:XN1wfp3ud7aG5gwkfifjasMT4z9V1jKzGgVEj6/mXazX10MvWX5lFPhR7r3PSIHWEVrxs8FJ8rVKzblMb1X1sFm73RORnE/EkfGV5ddPzkXnrAOQEsW6Aqt0tssmbsom43llqPjzIStOlZfBZIxbvm6sfuXhOLsWR9U+lK6/Zz0=,iv:KSuVg0OUS9zwh5Fb/jUetbFT6pQW0BF9WwAt0BQgvjc=,tag:6qNgv4W7ElruyuGG6KXI9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
