apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: github-token-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
- metadata:
    name: github
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: kubernetes.io/dockerconfigjson
  files:
  # content of dockerconfig.enc.token file should be replaced to yours
  - .dockerconfigjson=./dockerconfig.enc.token