apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../rollouts-base
- infrastructure.yaml
- frontend-rollout.yaml
- ingress.yaml
- ingress-preview.yaml

# more information: https://argo-rollouts.readthedocs.io/en/latest/features/kustomize/
openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
  target:
    kind: Rollout
    labelSelector: app.kubernetes.io/part-of=booking-microservices
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=booking-microservices
images:
- name: k8smaestro/argo-rollouts-demo
  newTag: green
- name: ghcr.io/kuchtek/course-bm-booking
  newTag: 1.1.0
- name: ghcr.io/kuchtek/course-bm-flight
  newTag: 1.1.0
- name: ghcr.io/kuchtek/course-bm-identity
  newTag: 1.1.0
- name: ghcr.io/kuchtek/course-bm-passenger
  newTag: 1.1.0